# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/docs/*

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- script: |
    python -m pip install --upgrade pip
    pip install mkdocs-material 
    mkdocs gh-deploy
  displayName: 'MkDocs Build'