# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - release
  paths:
    exclude:
    - deployment/azurepipelines/*
    - docs/*
    - src/docs/*

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'elentriek/restack-web'
    command: 'buildAndPush'
    dockerfile: '**/ReStack.Web/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/src/dotnet'
    tags: |
      latest
      $(Build.BuildId)